spring:
  application.name: secao_06
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_webest
    username: root
    password: eunaosei
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
