spring.application.name: secao_06
spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_webest?useTimezone=true&serverTimezone=UTC
      username: root
      password: eunaosei
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialet: org.hibernate.dialet.MYSQL8Dialect
      show-sql: false 